#!/bin/bash
# /etc/init.d/minecraft_server
# version 0.3.4 2015-08-15 (YYYY-MM-DD)

### BEGIN INIT INFO
# Provides:   Minecraft Server
# Required-Start: $local_fs $remote_fs
# Required-Stop:  $local_fs $remote_fs
# Should-Start:   $network
# Should-Stop:    $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:    Minecraft Server
# Description:    Starts a minecraft server
### END INIT INFO

#Settings
SERVICE='minecraft_server.jar'
OPTIONS='nogui'
USERNAME='minecraft'
MCPATH='/home/minecraft/server'
SERVERNAME='servername'
CPU_COUNT=1
INVOCATION="java -Xmx1536M -Xms1536M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=$CPU_COUNT -XX:+AggressiveOpts -jar $SERVICE $OPTIONS"

ME=`whoami`
as_user() {
  if [ $ME == $USERNAME ] ; then
    bash -c "$1"
  else
    su - $USERNAME -c "$1"
  fi
}

mc_start() {
  if as_user "screen -ls | grep $SERVERNAME > /dev/null"
  then
    echo "$SERVICE is already running!"
  else
    echo "Starting $SERVICE..."
    cd $MCPATH
    as_user "cd $MCPATH && screen -dmS $SERVERNAME $INVOCATION"
    sleep 7
    if as_user "screen -ls | grep $SERVERNAME > /dev/null"
    then
      echo "$SERVICE is now running."
    else
      echo "Error! Could not start $SERVICE!"
    fi
  fi
}

mc_stop() {
  if as_user "screen -ls | grep $SERVERNAME > /dev/null"
  then
    echo "Stopping $SERVICE"
    as_user "screen -p 0 -S $SERVERNAME -X eval 'stuff \"say SERVER SHUTTING DOWN IN 10 SECONDS. Saving map...\"\015'"
    as_user "screen -p 0 -S $SERVERNAME -X eval 'stuff \"save-all\"\015'"
    sleep 10
    as_user "screen -p 0 -S $SERVERNAME -X eval 'stuff \"stop\"\015'"
    sleep 7
  else
    echo "$SERVICE was not running."
  fi
  if as_user "screen -ls | grep $SERVERNAME > /dev/null"
  then
    echo "Error! $SERVICE could not be stopped."
  else
    echo "$SERVICE is stopped."
  fi
}

mc_update() {
  if as_user "screen -ls | grep $SERVERNAME > /dev/null"
  then
    echo "$SERVICE is running! Will not start update."
  else
    as_user "touch .jsawkrc"
    VER=`curl -s https://s3.amazonaws.com/Minecraft.Download/versions/versions.json | as_user "jsawk -n 'console.log(this.latest.release)'"`
    MC_SERVER_URL="https://s3.amazonaws.com/Minecraft.Download/versions/$VER/minecraft_server.$VER.jar"
    as_user "cd $MCPATH && wget -q -O $MCPATH/minecraft_server.jar.update $MC_SERVER_URL"
    if [ -f $MCPATH/minecraft_server.jar.update ]
    then
      if `diff $MCPATH/$SERVICE $MCPATH/minecraft_server.jar.update > /dev/null`
      then 
        echo "You are already running the latest version of $SERVICE."
      else
        as_user "mv $MCPATH/minecraft_server.jar.update $MCPATH/$SERVICE"
        echo "Minecraft successfully updated."
      fi
    else
      echo "Minecraft update could not be downloaded."
    fi
  fi
}

mc_command() {
  if [ "$1" ]
  then
    command="$1";
    if as_user "screen -ls | grep $SERVERNAME > /dev/null"
    then
      echo "$SERVICE is running... executing command"
      as_user "screen -p 0 -S $SERVERNAME -X eval 'stuff \"$command\"\015'"
    fi
    else
      echo "Must specify server command"
  fi
}

#Start-Stop here
case "$1" in
  start)
    mc_start
    ;;
  stop)
    mc_stop
    ;;
  restart)
    mc_stop
    mc_update
    mc_start
    ;;
  update)
    mc_stop
    mc_update
    mc_start
    ;;
  status)
    if as_user "screen -ls | grep $SERVERNAME > /dev/null"
    then
      echo "$SERVICE is running."
    else
      echo "$SERVICE is not running."
    fi
    ;;
  command)
    mc_command "$2"
    ;;

  *)
  echo "Usage: /etc/init.d/mc_survival {start|stop|update|status|restart|command \"server command\"}"
  exit 1
  ;;
esac

exit 0
